### ISSUE TITLE
doesn't seem to compile?

### ISSUE THREAD

**Issue by jvsteiner** [boinkor-net/tsnsrv#71]
./main.go:245:11: s.mux undefined (type *validTailnetSrv has no field or method mux)

I looked through the code, and I can't imagine how it would compile - also couldn't figure out what commit the docker container was compiled from to try and reverse engineer when this happened, but I glanced through the recent commit history, and it seems like this has been there a while...

**Comment by antifuchs** [comment]
How are you compiling this? The `mux` method on `validTailnetSrv` is defined in https://github.com/boinkor-net/tsnsrv/blob/main/proxy.go#L220, so if you're just running `go build main.go`, it won't pick up the proxy.go file.

**Comment by jvsteiner** [comment]
Ok, sorry - that's a rookie mistake.  Now I have to figure out why my IDE didn't find the method definition, but that is a separate issue...
